#!/usr/bin/env ts-node
/**
 * PDF Generation Probe Script
 * 
 * Uses pdf-lib to generate a simple PDF file on the filesystem to verify
 * library compatibility with the Node.js environment.
 * 
 * Per task requirements: Verify pdf-lib library compatibility with Node.js environment.
 * 
 * @module scripts/probes/probePdf
 */

// Note: pdf-lib should be installed
// For local testing: npm install --save-dev pdf-lib

import * as fs from 'fs';
import * as path from 'path';

// Import pdf-lib functions
let pdfLib;
try {
  pdfLib = await import('pdf-lib');
} catch (error) {
  console.error('❌ Error: pdf-lib package not found');
  console.error('   Install it with: npm install --save-dev pdf-lib');
  process.exit(1);
}

const OUTPUT_DIR = process.env.PDF_OUTPUT_DIR || './tmp';
const TEST_PDF_FILENAME = 'probe_test.pdf';

/**
 * Ensure output directory exists
 */
function ensureOutputDir(): void {
  try {
    if (!fs.existsSync(OUTPUT_DIR)) {
      fs.mkdirSync(OUTPUT_DIR, { recursive: true });
      console.log(`📁 Created output directory: ${OUTPUT_DIR}`);
    }
  } catch (error: any) {
    console.error('❌ Error creating output directory:');
    console.error('   ', error.message);
    throw error;
  }
}

/**
 * Generate a simple PDF document
 */
async function generateTestPDF(): Promise<Uint8Array> {
  console.log('📄 Generating test PDF...');
  console.log('');
  
  try {
    // Create a new PDF document
    const pdfDoc = await pdfLib.PDFDocument.create();
    
    // Add a page
    const page = pdfDoc.addPage([612, 792]); // US Letter size (8.5 x 11 inches)
    const { width, height } = page.getSize();
    
    // Add text to the page
    const fontSize = 30;
    page.drawText('PDF Generation Probe Test', {
      x: 50,
      y: height - 100,
      size: fontSize,
      color: pdfLib.rgb(0, 0, 0),
    });
    
    // Add more content
    page.drawText('This PDF was generated by the probe script to verify pdf-lib compatibility.', {
      x: 50,
      y: height - 150,
      size: 12,
      color: pdfLib.rgb(0.3, 0.3, 0.3),
    });
    
    // Add a rectangle
    page.drawRectangle({
      x: 50,
      y: height - 250,
      width: width - 100,
      height: 50,
      borderColor: pdfLib.rgb(0, 0, 1),
      borderWidth: 2,
    });
    
    // Add text inside the rectangle
    page.drawText('PDF Generation Successful!', {
      x: 60,
      y: height - 230,
      size: 14,
      color: pdfLib.rgb(0, 0, 1),
    });
    
    // Add metadata
    pdfDoc.setTitle('PDF Probe Test Document');
    pdfDoc.setAuthor('RoadDoggs Probe Script');
    pdfDoc.setSubject('PDF Library Compatibility Test');
    pdfDoc.setCreator('RoadDoggs PDF Probe');
    pdfDoc.setProducer('pdf-lib');
    
    // Serialize the PDF
    const pdfBytes = await pdfDoc.save();
    
    console.log('   ✓ PDF document created');
    console.log(`   Page size: ${width} x ${height} points`);
    console.log(`   PDF size: ${pdfBytes.length} bytes`);
    console.log('');
    
    return pdfBytes;
  } catch (error: any) {
    console.error('❌ Error generating PDF:');
    console.error('   ', error.message);
    console.error('');
    throw error;
  }
}

/**
 * Save PDF to filesystem
 */
async function savePDFToFile(pdfBytes: Uint8Array, filePath: string): Promise<void> {
  console.log('💾 Saving PDF to filesystem...');
  console.log(`   Path: ${filePath}`);
  console.log('');
  
  try {
    // Convert Uint8Array to Buffer for Node.js filesystem operations
    const buffer = Buffer.from(pdfBytes);
    
    // Write to file
    fs.writeFileSync(filePath, buffer, 'binary');
    
    // Verify file was created
    const stats = fs.statSync(filePath);
    
    console.log('   ✓ PDF saved successfully');
    console.log(`   File size: ${stats.size} bytes`);
    console.log(`   Created: ${stats.birthtime.toISOString()}`);
    console.log('');
  } catch (error: any) {
    console.error('❌ Error saving PDF to file:');
    console.error('   ', error.message);
    console.error('');
    throw error;
  }
}

/**
 * Verify PDF file is valid
 */
function verifyPDFFile(filePath: string): void {
  console.log('✅ Verifying PDF file...');
  console.log('');
  
  try {
    // Check if file exists
    if (!fs.existsSync(filePath)) {
      throw new Error('PDF file was not created');
    }
    
    // Read file and check PDF header
    const fileBuffer = fs.readFileSync(filePath);
    const header = fileBuffer.slice(0, 4).toString('ascii');
    
    // PDF files should start with %PDF
    if (header !== '%PDF') {
      throw new Error(`Invalid PDF header: expected "%PDF", got "${header}"`);
    }
    
    // Check file size
    const stats = fs.statSync(filePath);
    if (stats.size === 0) {
      throw new Error('PDF file is empty');
    }
    
    console.log('   ✓ File exists');
    console.log('   ✓ PDF header is valid (%PDF)');
    console.log(`   ✓ File size: ${stats.size} bytes`);
    console.log('');
    
    // Additional verification: check for PDF version
    const versionMatch = fileBuffer.toString('ascii', 0, 100).match(/%PDF-(\d\.\d)/);
    if (versionMatch) {
      console.log(`   ✓ PDF version: ${versionMatch[1]}`);
      console.log('');
    }
  } catch (error: any) {
    console.error('❌ Error verifying PDF file:');
    console.error('   ', error.message);
    console.error('');
    throw error;
  }
}

/**
 * Clean up test PDF file
 */
function cleanupTestFile(filePath: string): void {
  console.log('🧹 Cleaning up test PDF file...');
  
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      console.log('   ✓ Test PDF file deleted');
      console.log('');
    }
  } catch (error: any) {
    // Don't fail the probe if cleanup fails
    console.log('   ⚠️  Warning: Could not delete test PDF file');
    console.log('      ', error.message);
    console.log('');
  }
}

/**
 * Main probe function
 */
async function probePdf() {
  const outputPath = path.join(OUTPUT_DIR, TEST_PDF_FILENAME);
  
  try {
    console.log('🧪 Probing PDF Generation (pdf-lib)...');
    console.log('');
    
    // Ensure output directory exists
    ensureOutputDir();
    
    // Generate PDF
    const pdfBytes = await generateTestPDF();
    
    // Save to filesystem
    await savePDFToFile(pdfBytes, outputPath);
    
    // Verify file
    verifyPDFFile(outputPath);
    
    // Success summary
    console.log('✅ Probe successful!');
    console.log('   ✓ pdf-lib library imported successfully');
    console.log('   ✓ PDF document created');
    console.log('   ✓ PDF saved to filesystem');
    console.log('   ✓ PDF file is valid');
    console.log('   ✓ Library compatibility with Node.js verified');
    console.log('');
    
    // Display file path for user inspection
    console.log('📄 Test PDF created at:');
    console.log(`   ${path.resolve(outputPath)}`);
    console.log('');
    console.log('💡 You can open this file to verify the PDF content.');
    console.log('   The file will be cleaned up automatically.');
    console.log('');
    
    // Cleanup
    cleanupTestFile(outputPath);
    
    return true;
  } catch (error: any) {
    console.error('❌ Probe failed:');
    console.error('   Error message:', error.message);
    console.error('');
    console.error('💡 Troubleshooting:');
    console.error('   1. Verify pdf-lib is installed: npm install --save-dev pdf-lib');
    console.error('   2. Verify Node.js version is compatible (pdf-lib requires Node.js 12+)');
    console.error('   3. Check file system permissions for output directory');
    console.error('   4. Verify sufficient disk space');
    console.error('   5. Check for any TypeScript compilation errors');
    console.error('');
    
    // Try to cleanup on error
    cleanupTestFile(outputPath);
    
    process.exit(1);
  }
}

/**
 * Main probe execution
 */
async function main() {
  console.log('🚀 Starting PDF Generation Probe...\n');
  
  const success = await probePdf();
  
  if (success) {
    console.log('✅ PDF Generation probe completed successfully!');
    process.exit(0);
  } else {
    console.error('❌ PDF Generation probe failed!');
    process.exit(1);
  }
}

// Run probe
main().catch((error) => {
  console.error('💥 Fatal error running PDF Generation probe:', error);
  process.exit(1);
});
